openapi: 3.0.3
info:
  title: Categories API
  version: 1.0.0
  description: API for managing categories
  contact:
    name: Winston Spencer Sonnesen
    email: winston.sonnesen@fiap.com.br
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080/
    description: Local server
  - url: https://api.fiap.com.br/categories
    description: Production server
tags:
  - name: Categories
    description: Operations related to categories
paths:
  /categories:
    get:
      tags:
        - Categories
      summary: List all categories
      operationId: listCategories
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 0
            example: 1
        - name: perPage
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 10
            example: 10
      responses:
        "200":
          description: A list of categories
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedCategories"
    post:
      tags:
        - Categories
      summary: Create a new category
      operationId: createCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCategory"
      responses:
        "201":
          description: Category created
          headers:
            Location:
              schema:
                type: string
                format: uri
                example: /categories/123e4567-e89b-12d3-a456-426614174000
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"

  /categories/{categoryId}:
    get:
      tags:
        - Categories
      summary: Get a category by ID
      operationId: getCategory
      parameters:
        - name: categoryId
          in: path
          description: ID of the category to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Category found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "400":
          description: Bad request
        "404":
          description: Category not found
    put:
      tags:
        - Categories
      summary: Update a category
      operationId: updateCategory
      parameters:
        - name: categoryId
          in: path
          description: ID of the category to update
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCategory"
      responses:
        "200":
          description: Category updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "404":
          description: Category not found
    delete:
      tags:
        - Categories
      summary: Delete a category
      operationId: deleteCategory
      parameters:
        - name: categoryId
          in: path
          description: ID of the category to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Category deleted
        "400":
          description: Bad request
components:
  schemas:
    CreateCategory:
      required:
        - name
        - description
        - active
      type: object
      properties:
        name:
          type: string
          description: Name of the category
          maxLength: 100
          example: Eletronics
        description:
          type: string
          description: Description of the category
          maxLength: 255
          example: Eletronics products
        active:
          type: boolean
          description: Indicates if the category is active
          example: true
    UpdateCategory:
      required:
        - name
        - description
        - active
      type: object
      properties:
        name:
          type: string
          description: Name of the category
          maxLength: 100
          example: Eletronics
        description:
          type: string
          description: Description of the category
          maxLength: 255
          example: Eletronics products
        active:
          type: boolean
          description: Indicates if the category is active
          example: true
    PaginatedCategories:
      type: object
      properties:
        page:
          type: integer
          example: 1
        perPage:
          type: integer
          example: 10
        total:
          type: integer
          format: int64
          example: 100
        items:
          type: array
          items:
            $ref: "#/components/schemas/Category"
    Category:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID of the category
          example: 123e4567-e89b-12d3-a456-426614174000
        name:
          type: string
          description: Name of the category
          maxLength: 100
          example: Eletronics
        description:
          type: string
          description: Description of the category
          maxLength: 255
          example: Eletronics products
        active:
          type: boolean
          description: Indicates if the category is active
          example: true
        createdAt:
          type: string
          format: date-time
          description: Date and time when the category was created
          example: 2021-09-01T10:00:00
        updatedAt:
          type: string
          format: date-time
          description: Date and time when the category was updated
          example: 2021-09-01T10:00:00
        deletedAt:
          type: string
          format: date-time
          description: Date and time when the category was inactivated
          example: 2021-09-01T10:00:00
