POST http://localhost:8080/categories HTTP/1.1
content-type: application/json

{
    "name": "Category 1",
    "description": "Category 1 description"
}

###
POST http://localhost:8080/categories HTTP/1.1
content-type: application/json

{
    "name": "Category 2",
    "description": "Category 2 description"
}

###
POST http://localhost:8080/categories HTTP/1.1
content-type: application/json

{
    "name": "Category 3",
    "description": "Category 3 description"
}

###
GET http://localhost:8080/categories HTTP/1.1

###
GET http://localhost:8080/categories?page=3&perPage=5 HTTP/1.1

###
GET http://localhost:8080/categories/a92d1f1f-5cb2-4c8d-a344-d732d280ba66 HTTP/1.1

###
DELETE http://localhost:8080/categories/a92d1f1f-5cb2-4c8d-a344-d732d280ba66 HTTP/1.1

###
PUT http://localhost:8080/categories/4e16bd2f-9578-4acf-8468-c7e4367e8e7c HTTP/1.1
content-type: application/json

{
    "name": "Category 2 updated",
    "description": "Category 2 description updated"
}